"""initial_schema

Revision ID: 42deed428d85
Revises: 
Create Date: 2026-04-29 10:07:57.052880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42deed428d85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enphase_system_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('system_size_kw', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('panel_count', sa.Integer(), nullable=True),
    sa.Column('panel_wattage_w', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=128), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=False),
    sa.Column('tilt_angle_deg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('azimuth_deg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('degradation_rate', sa.Numeric(precision=5, scale=3), server_default='0.500', nullable=False),
    sa.Column('irradiance_source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enphase_system_id')
    )
    op.create_table('daily_summaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('production_kwh', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('consumption_kwh', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('peak_power_w', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('peak_power_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interval_count', sa.Integer(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_id', 'day')
    )
    op.create_table('energy_intervals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), server_default='900', nullable=False),
    sa.Column('production_wh', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('consumption_wh', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('net_wh', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_id', 'interval_start')
    )
    op.create_table('irradiance',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('ghi_kwh_m2', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('dni_kwh_m2', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('poa_kwh_m2', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_id', 'day', 'source')
    )
    op.create_table('monthly_summaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('production_kwh', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('theoretical_kwh', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('performance_ratio', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('expected_pr', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('anomaly_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_id', 'month')
    )
    op.create_table('poll_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('poll_type', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('records_fetched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_inserted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('date_range_start', sa.Date(), nullable=True),
    sa.Column('date_range_end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll_log')
    op.drop_table('monthly_summaries')
    op.drop_table('irradiance')
    op.drop_table('energy_intervals')
    op.drop_table('daily_summaries')
    op.drop_table('systems')
    # ### end Alembic commands ###
